AllCops:
  # Rubyのバージョンを指定
  TargetRubyVersion: 2.4.1
  # 除外するファイル
  Exclude:
    - vendor/bundle/**/*
    - bin/*
    - db/**/*
    - config/**/*
    - Gemfile

# Missing magic comment # frozen_string_literal: true. を無視
Style/FrozenStringLiteralComment:
  Enabled: false

# Missing top-level class documentation comment. を無視
Style/Documentation:
  Enabled: false

# Line is too long を無視
Metrics/LineLength:
  Max: 128

# Block has too many lines を無視
Metrics/BlockLength:
  Enabled: false

# Method has too many lines を無視
Metrics/MethodLength:
  Enabled: false

# Parenthesize the param を無視
Lint/AmbiguousBlockAssociation:
  Enabled: false
